spring:
  datasource:
    url: jdbc:mysql://localhost:3307/movie_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.movieplatform.domain
  configuration:
    map-underscore-to-camel-case: true

